### ISSUE TITLE
TypeError when using mongoengine

### ISSUE THREAD

**Issue by lucassimon994** [bruth/restlib2#6]
I have a model defined in mongoengine as

```
from mongoengine import *
import datetime

class Blog(Document):
    post_id = IntField(unique=True)
title = StringField(max_length=144, required=True)
date_created = DateTimeField(default=datetime.datetime.now)
body = StringField(required=True)
```

with the urls.py file as

```
from django.conf.urls import patterns, include, url
from .views import *

urlpatterns = patterns('',
url(r'^$', BlogResource)
)
```

and the views.py as

```
import json
from .models import *
from restlib2.resources import *
from preserialize import serialize

class BlogResource(Resource):
supported_accept_methods = ['application/json']

def get(self, request):
    blog_template = {
        'fields': ['post_id', 'title', 'date_created', 'body']
    }
    data = serialize(Blog.objects(), **blog_template)
    return json.dumps(data)
```

But I am receiving the error

```
Internal Server Error: /blog/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/restlib2/resources.py", line 100, in __call__
    return instance.__call__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/restlib2/resources.py", line 258, in __call__
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/restlib2/resources.py", line 269, in dispatch
    response = method_handler(request, *args, **kwargs)
  File "/home/lucas/Programming/Python/Django/MongoRest/mongoblog/blog/views.py", line 13, in get
    data = serialize(Blog.objects(), **blog_template)
TypeError: 'module' object is not callable
[26/Jun/2013 14:48:59] "GET /blog/ HTTP/1.1" 500 95851
```

I am almost certain that this is a bug between restlib2 and mongoengine.

Now that I fixed the Traceback error, and added data into mongo by entering in the console

```
>>> post1 = Blog(post_id=1, title='Introduction to OpenCL', body='OpenCL is an API which allows access to     arbitrary hardware. It allows people to develop highly parallele applications with ease.')
>>> post1.save()
>>> post = Blog(post_id=2, title='Introduction to C', body='C is a highly flexible systems programming language which allows for any type of programming paradigm to be implemented.')
>>> post.save()
```

When I visit http://127.0.0.1:5000/blog, I am given an object with no field data, just

```
[["id", "post_id", "title", "date_created", "body"], ["id", "post_id", "title", "date_created", "body"]]
```

Also, in the console, I receive errors about preserialize

```
>>> from preserialize.serialize import serialize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/preserialize/serialize.py", line 2, in <module>
    from django.db import models
  File "/usr/lib/python2.7/site-packages/django/db/__init__.py", line 11, in <module>
    if settings.DATABASES and DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You     must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing     settings.
```

**Comment by bruth** [comment]
You missed one import depth.. `from preserialize.serialize import serialize`. It's obnoxious I know, I need to fix it.

**Comment by lucassimon994** [comment]
Ah, that fixes it thank you. Do you have any examples of a Resource that respondes to get, post, and patch requests?

**Comment by lucassimon994** [comment]
Also, the full code is located at
https://github.com/lucassimon994/mongo_blog

**Comment by bruth** [comment]
Here is an example of a few methods: https://github.com/cbmi/serrano/blob/2.x/serrano/resources/context.py#L119-L163
